### ISSUE TITLE
Can't find asset files in salad.init

### ISSUE THREAD

**Issue by hiasr** [bluzky/salad_ui#64]
When following the steps in the readme, I get the following exception when executing `mix salad.init`

```bash
$ mix salad.init
Enter the path to the components folder (lib/glhub_web/components):
Select the color scheme to use (gray): green
Using color scheme: green
Writing components path to dev.exs
Writing tails config to config.exs
Patching app.css
** (File.Error) could not read file "/home/hiasr/code/glhub/_build/dev/lib/salad_ui/priv/static/assets/colors/green.css": no such file or directory
    (elixir 1.16.3) lib/file.ex:384: File.read!/1
    (salad_ui 0.9.0) lib/salad_ui/patcher/css_patcher.ex:8: SaladUI.Patcher.CSSPatcher.patch/2
    (salad_ui 0.9.0) lib/mix/tasks/salad.init.ex:138: Mix.Tasks.Salad.Init.patch_css/2
    (salad_ui 0.9.0) lib/mix/tasks/salad.init.ex:45: Mix.Tasks.Salad.Init.init/3
    (mix 1.16.3) lib/mix/task.ex:478: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.16.3) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /nix/store/wg94j29n69xjidwsgnm2274ljw3lwlcn-elixir-1.16.3/bin/mix:2: (file)
```

When looking in the build directory, I only found the following files:
```bash
$ ls _build/dev/lib/salad_ui
ebin
```

Thank you for your help in advance!

**Comment by daic0r** [comment]
Having the exact same problem, was just going to try out SaladUI.

**Comment by bluzky** [comment]
@hiasr , @daic0r Thanks for reporting this issue. This caused by missing package config when publish to hex.
Please try again with version "0.10.0", in this version, I also release `Accordion` too
