### ISSUE TITLE
Mix task salad.init not working in app deployed with releases

### ISSUE THREAD

**Issue by tylerbarker** [bluzky/salad_ui#66]
Hey, thanks for this library!

I'm running into issues trying the Mix tasks `mix salad.init` and `mix.salad.init --as-lib`. The task gets some of the way there but it blows up on "Patching app.css".

This is happening in development, not yet tested in prod. I'm using Elixir 1.17.2 via ASDF. See this error:
```
Using color scheme: zinc
Writing components path to dev.exs
Writing tails config to config.exs
Patching app.css
** (File.Error) could not read file "/Users/me/elixirland/my_app/_build/dev/lib/salad_ui/priv/static/assets/colors/zinc.css": no such file or directory
    (elixir 1.17.2) lib/file.ex:385: File.read!/1
    (salad_ui 0.9.0) lib/salad_ui/patcher/css_patcher.ex:8: SaladUI.Patcher.CSSPatcher.patch/2
    (salad_ui 0.9.0) lib/mix/tasks/salad.init.ex:138: Mix.Tasks.Salad.Init.patch_css/2
    (salad_ui 0.9.0) lib/mix/tasks/salad.init.ex:45: Mix.Tasks.Salad.Init.init/3
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (mix 1.17.2) lib/mix/cli.ex:96: Mix.CLI.run_task/2
    /Users/me/.asdf/installs/elixir/1.17.2-otp-27/bin/mix:2: (file)
```

If I go to my `_build/dev/lib/salad_ui/` only two things are found within:
* `.mix/` - contains `compile.elixir` etc
* `ebin/` - full of `.beam` files and `salad_ui.app`

Hope that helps investigation, let me know if I could provide any additional info for you. Cheers ✌️

**Comment by bluzky** [comment]
Hi @tylerbarker pls try with Salad v0.10 which released yesterday.

**Comment by bluzky** [comment]
I forgot to update README :D

**Comment by tylerbarker** [comment]
Ah thanks! That fixed it :)
